### ISSUE TITLE
Error api_host after update to 1.2.7

### ISSUE THREAD

**Issue by aludkov** [mailgun/mailgun-ruby#275]
On  1.2.6 is all Ok!
After update to 1.2.7, error  = undefined method `api_host' for Mailgun:Module

**Comment by Linuus** [comment]
YEs, 1.2.7 is broken. I have opened a PR here https://github.com/mailgun/mailgun-ruby/pull/274

**Comment by Retttro** [comment]
@Linuus Thank you for the fix. PR is merged and the new version 1.2.8 is released. Closing.
