### ISSUE TITLE
Invalid delivery method

### ISSUE THREAD

**Issue by fadynaffa3** [mailgun/mailgun-ruby#105]
I am getting this error after commenting out `config.action_mailer.mailgun_settings` as it was raising `undefined method `mailgun_settings=' for ActionMailer::Base:Class`

Configuration:

- Rails 4.2.8
- Ruby 2.4.1
- mailgun-ruby 1.1.6

* Error Message is Invalid delivery method mailgin

**Comment by pirogoeth** [comment]
@fadynaffa3 Could you try with Rails >= 5.0.0.1? I've got a [sample application using Railgun](https://github.com/pirogoeth/railgun-sample) that may help you set things up.

**Comment by fadynaffa3** [comment]
@pirogoeth already tried with rails 5 before and worked correctly but the issue is on rails 4.2.8 and the documentation didn't mention the supported rails version and it's confusing.
I can't update my project to rails 5 in one day to test mailgun usage with action_mailer

**Comment by pirogoeth** [comment]
@fadynaffa3 I will see what I need to do to make it work with Rails 4.2.8.

**Comment by fadynaffa3** [comment]
Thanks :)

**Comment by ivko999** [comment]
Any luck with this?

**Comment by fadynaffa3** [comment]
@ivko999 try this:
`ActionMailer::Base.add_delivery_method(:mailgun, Mailgun, default_options={})`

**Comment by Benjamin-Dobell** [comment]
This is Rails bug, same underlying cause as #104. Fixed by pending Rails PR https://github.com/rails/rails/pull/35419

**Comment by Benjamin-Dobell** [comment]
Should probably note there is an issue with this Gem as well, as it's causing `ActionMailer::Base` to autoload earlier than it ought to. Fixed in PR https://github.com/mailgun/mailgun-ruby/pull/162.

**Comment by Retttro** [comment]
Version 1.2.4 with the fix was published to rubygems. Closing.
